### ISSUE TITLE
TypeError: 'NoneType'

### ISSUE THREAD

**Issue by ghost** [drybalka/wal-theme-picker#2]
An attempt to run the script gives the following:

Traceback (most recent call last):
  File "/home/me/software/wal-theme-picker/./wal-theme-picker.py", line 208, in <module>
    counts, colors = get_image_colors(args)
  File "/home/me/software/wal-theme-picker/./wal-theme-picker.py", line 27, in get_image_colors
    counts = [el[0] for el in tally]
TypeError: 'NoneType' object is not iterable

**Comment by drybalka** [comment]
Yes, that was probably due to image having more than 256 different colors. It should be fixed with the newest commit.
